"""add login throttles

Revision ID: a5c70d7ccfe2
Revises: 877dd7756903
Create Date: 2026-09-23 16:34:37.629545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.db.types


revision: str = 'a5c70d7ccfe2'
down_revision: Union[str, None] = '877dd7756903'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_throttles',
    sa.Column('key', sa.String(length=320), nullable=False),
    sa.Column('failures', sa.Integer(), nullable=False),
    sa.Column('window_started_at', app.db.types.TZDateTime(timezone=True), nullable=False),
    sa.Column('locked_until', app.db.types.TZDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('login_throttles')
    # ### end Alembic commands ###
